# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Docker Image
        run: docker build -t pushshift_fetch .
      
      - name: Authenticate AWS ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 802265574332.dkr.ecr.us-west-2.amazonaws.com    

      - name: Tag and push container to ECR
        run: |
          docker tag pushshift-fetch:latest 1802265574332.dkr.ecr.us-west-2.amazonaws.com/pushshift-fetch:latest
          docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/pushshift-fetch:latest        
